Add forgejo runners

diff --git a/ansible/roles/takel_ship_forgejo/templates/run-postinstall.forgejo-server.bash.j2 b/ansible/roles/takel_ship_forgejo/templates/run-postinstall.forgejo-server.bash.j2
--- a/ansible/roles/takel_ship_forgejo/templates/run-postinstall.forgejo-server.bash.j2
+++ b/ansible/roles/takel_ship_forgejo/templates/run-postinstall.forgejo-server.bash.j2
@@ -1,24 +1,31 @@
 {{ takel_ship_scripts_shebang }}
 
 RETRY=1
-# get users
-until [ $RETRY -ge 20 ] || (forgejo admin user list); do
+# wait until the server is up
+until [ $RETRY -ge 20 ] || forgejo admin user list; do
   echo Forgejo server not ready. Retrying in a second...
   sleep 1
-  RETRY=$RETRY+1
+  let RETRY++
 done
 
 USERLIST=$(forgejo admin user list)
 
-# if the forgejo command failed or
-# if there is no @-sign in the user list
-if [ $? -ne 0 ] || [[ "$USERLIST" = *@* ]]; then
-  exit
-fi
+# if the forgejo command failed then exit
+[ $? -ne 0 ] && exit
 
-echo Creating Forgejo admin account
+# if there is a @-sign in the user list then exit
+[[ "$USERLIST" = *@* ]] && exit
+
+echo Creating forgejo admin account
 forgejo admin user create \
   --admin \
   --username ${TAKELSHIP_FORGEJO_SERVER_ADMIN_NAME:-{{ takel_ship_forgejo_admin['name'] }}} \
   --password ${TAKELSHIP_FORGEJO_SERVER_ADMIN_PASSWORD:-{{ takel_ship_forgejo_admin['password'] }}} \
   --email ${TAKELSHIP_FORGEJO_SERVER_ADMIN_EMAIL:-{{ takel_ship_forgejo_admin['email'] }}}
+
+echo Creating forgejo access token
+forgejo admin user generate-access-token \
+  --token-name fortea \
+  --username administrator \
+  --scopes all \
+  --raw > {{ takel_ship_forgejo_fortea_token_file }}
